# Generated by Django 5.1.6 on 2025-03-02 12:14

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='color',
            field=models.CharField(default=users.models.generate_pastel_color, editable=False, max_length=7),
        ),
    ]
