# Generated by Django 5.1.6 on 2025-03-13 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('Not Specified', 'Not Specified'), ('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Not Specified', max_length=15),
        ),
    ]
